"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY: read secret key from environment in production
SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "django-insecure-+!&h80p_ps^w+6-f-z^$$bb)i5*4p$r4r$mzxd_4((!o1$(wmb",
)

# DEBUG should be explicitly set via environment variable. Default is False.
DEBUG = os.environ.get("DEBUG", "False").lower() in ("true", "1", "yes")

# Allow hosts via env (comma-separated), with safe defaults for local dev
ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get(
        "ALLOWED_HOSTS", "localhost,127.0.0.1,.onrender.com"
    ).split(",")
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    "jazzmin",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'contact',
    'rest_framework',
    'portfolio',
    'corsheaders',

]
INSTALLED_APPS += [
    "cloudinary",
    "cloudinary_storage",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {}
DATABASE_URL = os.environ.get("DATABASE_URL")
if DATABASE_URL:
    import dj_database_url
    DATABASES["default"] = dj_database_url.parse(DATABASE_URL, conn_max_age=600)
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
CORS_ALLOW_ALL_ORIGINS = True

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

JAZZMIN_SETTINGS = {
    # ================= BRANDING =================
    "site_title": "Portfolio Admin",
    "site_header": "Idrissa Dashboard",
    "site_brand": "Portfolio System",
    "welcome_sign": "Welcome back 👋 Idrissa",
    "copyright": "Idrissa Yahya",
     "show_recent_actions": False,

    # ================= UI =================
    "site_logo": None,
    "site_logo_classes": "img-circle",
    "site_icon": "fas fa-code",

    "search_model": ["portfolio.Project", "portfolio.ContactMessage"],

    # ================= NAVIGATION =================
    "topmenu_links": [
        {"name": "Dashboard", "url": "admin:index"},
        {"model": "portfolio.project"},
        {"model": "portfolio.contactmessage"},
    ],

    "show_sidebar": True,
    "navigation_expanded": True,

    # ================= ORDER SIDEBAR =================
    "order_with_respect_to": [
        "portfolio",
        "auth",
    ],

    # ================= ICONS =================
    "icons": {
        "auth": "fas fa-users-cog",

        "portfolio.Project": "fas fa-code",
        "portfolio.Skill": "fas fa-bolt",
        "portfolio.About": "fas fa-user",
        "portfolio.Certificate": "fas fa-certificate",
        "portfolio.Tool": "fas fa-tools",
        "portfolio.Education": "fas fa-graduation-cap",
        "portfolio.Experience": "fas fa-briefcase",
        "portfolio.ContactMessage": "fas fa-envelope",
    },

    # ================= UI LAYOUT =================
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "portfolio.Project": "collapsible",
        "portfolio.ContactMessage": "collapsible",
    },

    # ================= THEMES =================
    "theme": "darkly",   # try: "cosmo", "flatly", "darkly"
    



    "custom_links": {
    "portfolio": [
        {
            "name": "Custom Dashboard",
            "url": "/admin/dashboard/",
            "icon": "fas fa-chart-line",
        }
    ]
},

}






JAZZMIN_UI_TWEAKS = {
    
    "navbar_small_text": False,
    "footer_small_text": True,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-primary",
    "accent": "accent-info",
    "navbar": "navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",
    "dark_mode_theme": "darkly",
    
    

}



import cloudinary

CLOUDINARY_STORAGE = {
    "CLOUD_NAME": os.environ.get("CLOUDINARY_CLOUD_NAME", "dyxnjsbjc"),
    "API_KEY": os.environ.get("CLOUDINARY_API_KEY", "833468996564241"),
    "API_SECRET": os.environ.get("CLOUDINARY_API_SECRET", "Jxo9Kg1DiFJt9Q-VMdvVSIvyTpU"),
}

DEFAULT_FILE_STORAGE = "cloudinary_storage.storage.MediaCloudinaryStorage"




MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

CSRF_TRUSTED_ORIGINS = [
    host.strip()
    for host in os.environ.get("CSRF_TRUSTED_ORIGINS", "").split(",")
    if host.strip()
]

# Security settings for production
if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_SSL_REDIRECT = os.environ.get("SECURE_SSL_REDIRECT", "False").lower() in (
        "true",
        "1",
        "yes",
    )
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

USE_WHITENOISE = os.environ.get("USE_WHITENOISE", "False").lower() in ("true", "1", "yes")
if USE_WHITENOISE:
    MIDDLEWARE.insert(1, "whitenoise.middleware.WhiteNoiseMiddleware")
    STATICFILES_STORAGE = os.environ.get(
        "STATICFILES_STORAGE", "whitenoise.storage.CompressedManifestStaticFilesStorage"
    )